#!/usr/bin/env python
import argparse


parser = argparse.ArgumentParser()
subparser = parser.add_subparsers()

add = subparser.add_parser('add')
commit = subparser.add_parser('commit')

add.add_argument('-p', '--patch', action='store_true', help='add patch')
commit.add_argument('-m', '--message', help='commit message')

args = parser.parse_args()

print(args)
